#!/usr/bin/env bash



###############################################################################
#
# Intro:
# 	Automatically find the ideal JPEG quality setting for a JPEG image by
#	calculating the output images dissimilarity from the input JPEG. This
# 	frees us from having to rely on the unstandardized quality integer.
#
# Installation instructions:
#	Place this script anywhere in your $PATH. Requires Bash >= 4.x
#
# Required tools:
#	* dssim - https://github.com/pornel/dssim
#	* jpegoptim - https://github.com/tjko/jpegoptim
#	* mozjpeg - https://github.com/mozilla/mozjpeg
#
# CLI usage example:
# 	cjpegd  /path/to/input-image.jpg
#
# Supported encoders:
#	* jpegoptim
#	* mozjpeg
#
###############################################################################

#Set Script Name variable
SCRIPT=`basename ${BASH_SOURCE[0]}`

#Initialize variables to default values.
OPT_D="~/Pictures/compressed"

#Set fonts for Help.
NORM=`tput sgr0`
BOLD=`tput bold`
REV=`tput smso`

#Help function
function HELP {
  echo -e \\n"Help documentation for ${BOLD}${SCRIPT}.${NORM}"\\n
  echo -e "${REV}Basic usage:${NORM} ${BOLD}$SCRIPT file.ext${NORM}"\\n
  echo "Command line switches are optional. The following switches are recognized."
  echo "${REV}-d${NORM}  --Sets the value for option ${BOLD}d${NORM}. Default is ${BOLD}D${NORM}."
  echo -e "${REV}-h${NORM}  --Displays this help message. No further functions are performed."\\n
  echo -e "Example: ${BOLD}$SCRIPT  -d /dist/images file.jpg${NORM}"\\n
  exit 1
}

#Check the number of arguments. If none are passed, print help and exit.
NUMARGS=$#
echo -e \\n"Number of arguments: $NUMARGS"
if [ $NUMARGS -eq 0 ]; then
  HELP
fi

### Start getopts code ###

#Parse command line flags
#If an option should be followed by an argument, it should be followed by a ":".
#Notice there is no ":" after "h". The leading ":" suppresses error messages from
#getopts. This is required to get my unrecognized option code to work.

while getopts :d:h FLAG; do
  case $FLAG in
    d)  #set option "d"
      OPT_D=$OPTARG
      echo "-d used: $OPTARG"
      echo "OPT_D = $OPT_D"
      ;;
    h)  #show help
      HELP
      ;;
    \?) #unrecognized option - show help
      echo -e \\n"Option -${BOLD}$OPTARG${NORM} not allowed."
      HELP
      #If you just want to display a simple error message instead of the full
      #help, remove the 2 lines above and uncomment the 2 lines below.
      #echo -e "Use ${BOLD}$SCRIPT -h${NORM} to see the help documentation."\\n
      #exit 2
      ;;
  esac
done

shift $((OPTIND-1))  #This tells getopts to move on to the next argument.

### End getopts code ###

###############################################################################
# SANITY CHECKS
###############################################################################

# Set locales to C (raw uninterpreted byte sequence) to avoid illegal byte sequence errors and invalid number errors
export LANG=C LC_NUMERIC=C LC_COLLATE=C

# Check for proper input parameters
# Filename and selected JPEG compressor should both be set
if [ -z $1 ]; then
	echo "Please select a input JPEG"
    exit 1
fi
if [ -n $1 ]; then
	INPUTFILE="$1"
else
	exit 1
fi

# Path and filename retrieval to save the output image
CLEANFILENAME=${INPUTFILE%.jp*g}
FILEEXTENSION=${INPUTFILE##*.}

if [ -z $2 ]; then
    CLEANPATH="${INPUTFILE%/*}"
else
    CLEANPATH="$2"
    CLEANPATH="${CLEANPATH%/*}"
fi


# If the JPEG is in the same direcctory, empty the path variable
# Or if it is set, make sure the path has a trailing slash
if [ "$CLEANPATH" == "$INPUTFILE" ]; then
	CLEANPATH=""
else
	CLEANPATH="$CLEANPATH/"
fi

###############################################################################
# CONFIGURABLE RUNTIME VARIABLES
###############################################################################

# Initial JPEG quality and summand/subtrahend settings to start from
INITIAL_JPEG_QUALITY="80"
JPEG_QUALITY_SUMMAND_SUBTRAHEND="20"

# The dissimilarity range in which we accept a recompressed JPEG image
DSSIM_LOWER_BOUND="0.014250"
DSSIM_UPPER_BOUND="0.016500"
JPEG_COMPRESSION_COMMAND="cjpeg -quality \${__current_jpeg_quality} -dct float \${INPUTFILE}"

# How should the output image name be amended - Leave empty to overwrite
if [ -z $2 ]; then
    OUTPUTFILESUFFIX="_dssim"
fi

###############################################################################
# MAIN PROGRAM
###############################################################################

main () {
#	define_encoder_toolbelt
	local -i __current_jpeg_quality=$(optimize_quality_level ${INITIAL_JPEG_QUALITY} ${JPEG_QUALITY_SUMMAND_SUBTRAHEND})
	$(eval ${JPEG_COMPRESSION_COMMAND} > "${CLEANPATH}${CLEANFILENAME##*/}${OUTPUTFILESUFFIX}".${FILEEXTENSION});
}



###############################################################################
# FUNCTIONS
###############################################################################

function define_encoder_toolbelt () {
	# Define our toolbelt of JPEG compression commands and make them selectable from the CLI
	case ${JPEG_COMPRESSION_SELECTION} in
		"jpegoptim") JPEG_COMPRESSION_COMMAND="jpegoptim -q -p -f --max=\${__current_jpeg_quality} --strip-all --all-progressive --stdout \${INPUTFILE}";;
		"mozjpeg") JPEG_COMPRESSION_COMMAND="cjpeg -quality \${__current_jpeg_quality} -dct float \${INPUTFILE}";;
	   *) echo "Supported JPEG compression methods: jpegoptim | mozjpeg"; exit 1;;
	esac
}

function optimize_quality_level () {
	local -i __current_jpeg_quality=$1
	local -i __current_jpeg_quality_summand_subtrahend=$2
	local -i __iteration_counter="0"
	local __current_dssim_score="0"
	# While the result of the current run is either too similar (ecouraging stronger compression) or too different (already too many artifacts visible), run the compression again while homing in on a proper quality setting for the current encoder
	while ( (( $(echo "${__current_dssim_score} >= ${DSSIM_UPPER_BOUND}" | bc -l) )) || (( $(echo "${__current_dssim_score} < ${DSSIM_LOWER_BOUND}" | bc -l) )) ) && (( ${__iteration_counter}<7 )); do
		# Retrieve the current dissimilarity score
		__current_dssim_score=$(calculate_dissimilarity "${__current_jpeg_quality}")
		# Define if we need to add or substract from the current JPEG quality (DRY)
		if (( $(echo "${__current_dssim_score} < ${DSSIM_LOWER_BOUND}" | bc -l) )); then
			local __arithmetic_operator="-"
		elif (( $(echo "${__current_dssim_score} >= ${DSSIM_UPPER_BOUND}" | bc -l) )); then
			local __arithmetic_operator="+"
		fi
		# Binary-search-esque approach to home in on an acceptable JPEG quality by halfing the summand/subtrahend
		__current_jpeg_quality_summand_subtrahend=$(echo "scale=0; ${__current_jpeg_quality_summand_subtrahend}/2" | bc -l)
		if (( ${__current_jpeg_quality_summand_subtrahend}==0 )); then
			__current_jpeg_quality_summand_subtrahend="1"
		fi
		# Set the JPEG quality to the newly calculated value
		__current_jpeg_quality=$(echo "scale=0; ${__current_jpeg_quality}${__arithmetic_operator}${__current_jpeg_quality_summand_subtrahend}" | bc -l)
		(( __iteration_counter++ ))
	done
	echo ${__current_jpeg_quality}
}

function calculate_dissimilarity () {
	local __current_jpeg_quality=$1
	# Convert the original JPEG to PNG for DSSIM comparison
	# Also base64 it so we can safely store its result in a variable without needing to write the file to disk
	local __original_image_png_base64=$(convert "${INPUTFILE}" png:- | base64)
	# Run the JPEG compressor, pipe its output to convert, create a PNG from the newly compressed JPEG and hand it to DSSIM for comparison - all without creating a file on disk to increase runtime performance
	local __current_dissimilarity=$(eval ${JPEG_COMPRESSION_COMMAND} | convert - png:- | dssim <(echo "${__original_image_png_base64}" | base64 --decode) /dev/stdin | awk '{print $1}')
	echo ${__current_dissimilarity}
}

main