#!/usr/bin/env bash

# Check for proper input parameters
# Filename and folder should both be set
    files="$1"
	folder="$2"



shopt -s nullglob

 for f in *.jpg; do
	echo "/home/lesi/repos/cjpeg-dssim/cjpegd $f $1"
    /home/lesi/repos/cjpeg-dssim/cjpegd $f $1
 done
